#!/usr/bin/env python3

"""
## Main Info

1. Block size(sector size): 512b
2. Minimal FAT32 partition: 65527s
3. Each partittion start sector should be a multiply of 2048 for good performance
4. GPT no logical partition
5. Maximum number of GPT partitions is 128
"""

import os
import sys
import yaml
import importlib

import lib.storage
import lib.base_storage_entities
import lib.configuration_generators


def calculate_complete_layout(layout: dict) -> lib.storage:
    storage_module = importlib.import_module(f"lib.{layout["label"]}_storage")

    complete_layout = storage_module.Storage(
        layout["sector_size"], layout["size_in_bytes"]
    )

    partitions = layout["partitions"]

    complete_layout.append(
        lib.base_storage_entities.Alignment(complete_layout.sector),
        "none"
    )

    for name, partition_info in partitions.items():
        print(f"Processing partition: {name}")

        match partition_info:
            case list():
                extended_partition_start_block = complete_layout.sector

                for logical_partition in partition_info:
                    for logical_partition_name, logical_partition_info in logical_partition.items():
                        print(f"Processing logical partition: {logical_partition_name}")

                        complete_layout.append(
                            lib.base_storage_entities.Alignment(complete_layout.sector),
                            "none"
                        )
                        complete_layout.append(
                            lib.base_storage_entities.InPlacePartition(
                                logical_partition_name, start_sector=complete_layout.sector,
                                **logical_partition_info
                            ),
                            "logical"
                        )

                complete_layout.append(
                    lib.base_storage_entities.ExtendedPartition(
                        name, extended_partition_start_block, complete_layout.sector
                    ),
                    "primary"
                )

            case dict():
                complete_layout.append(
                    lib.base_storage_entities.InPlacePartition(
                        name, start_sector=complete_layout.sector, **partition_info
                    ),
                    "primary"
                )

    return complete_layout


def load_layout_conf(layout_path: str) -> dict:
    with open(layout_path) as layout_conf:
        return yaml.safe_load(layout_conf)


def form_out_path(layout_path: str) -> str:
    layout_path_no_ext, _ = os.path.splitext(layout_path)
    out_dir_path = f"{os.path.dirname(layout_path_no_ext)}/{os.path.basename(layout_path_no_ext)}_out"

    os.mkdir(out_dir_path)

    return f"{out_dir_path}/{os.path.basename(layout_path_no_ext)}"


def main(layout_path: str):
    layout: dict = load_layout_conf(layout_path)
    out_file_path_prefix: str = form_out_path(layout_path)
    complete_layout = calculate_complete_layout(layout["flash"])

    config_generator = lib.configuration_generators.ConfigurationsGenerator(
        complete_layout, out_file_path_prefix
    )

    for config_name in layout["configs"]:
        configurator = getattr(config_generator, f"_iface_{config_name}", None)
        if configurator is None:
            print(f"Warning: configurator {config_name} not found")
        else:
            configurator()


if __name__ == "__main__":
    # try:
        main(*sys.argv[1:])
    # except TypeError as exc:
    #     print(exc)
    #     exit(1)
